remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: Oliver's homepage
description: Bookmark this to keep an eye on my project updates!
description: I plan on trying to add images
![Book logo](./assets/logo.png)
